### PR TITLE
Fix/logs when missing pkg

### LINKED ISSUE #1069: Error message should be displayed when no lambdapi.pkg is found
As documented in https://lambdapi.readthedocs.io/en/latest/module.html, a lambdapi.pkg must be placed at the root of the source tree of a library under development. When used with the command line, the absence of this file rises an error. However, when used with editors (both Vscode and Emacs), no error is displayed.

Thus, it is important that whenever the lambdapi.pkg file is missing, the editors should display an error message when navigating the proofs.

### PR DESCRIPTION
**Pull request by Alidra**
As documented in https://lambdapi.readthedocs.io/en/latest/module.html, a lambdapi.pkg must be placed at the root of the source tree of a library under development. When used with the command line, the absence of this file rises an error. However, when used with editors (both Vscode and Emacs), no error is displayed.

This PR fixes #1069

### CODE REVIEW

File: src/lsp/lp_doc.ml [hunk 1]
```diff
@@ -153,20 +164,27 @@ let dummy_loc =
 
 let check_text ~doc =
   let uri, version = doc.uri, doc.version in
+  let root =
+    match doc.root with
+    | Some(ss) -> ss
+    | None ->
+      raise(Error.fatal_no_pos "Root signature is missing
```
Comment (fblanqui) [inline src/lsp/lp_doc.ml:171]: signature -> state

File: src/lsp/lp_doc.ml [hunk 2]
```diff
@@ -153,20 +164,27 @@ let dummy_loc =
...
+      probably because new_doc has raised exception")
```
Comment (fblanqui) [inline src/lsp/lp_doc.ml:172]: Just to know: will this error message be printed somewhere in the editor?

File: src/lsp/lp_lsp.ml [hunk 3]
```diff
@@ -382,36 +406,39 @@ let hover_symInfo ofmt ~id params =
...
-    (Range.column start - 1),
-    (Range.line finish - 1),
-    (Range.column finish - 1)
-  in
+  try
+    (* The information about the tokens is stored *)
+    let sym =
+      match doc.final with
+      | Some ss -> Pure.get_symbols ss
+      | None    -> raise (Error.fatal_no_pos("Horror")) in
```
Comment (fblanqui) [inline src/lsp/lp_lsp.ml:414]: Just to know: will this error message be printed somewhere in the editor?

**Review by fblanqui — CHANGES_REQUESTED** [review]

File: src/lsp/lp_doc.ml (hunk 1 above)
Comment (Alidra) [reply src/lsp/lp_doc.ml]: Done.

File: src/lsp/lp_doc.ml (hunk 2 above)
Comment (Alidra) [reply src/lsp/lp_doc.ml:172]: Not displayed in the editor but will be written in the /tmp/lambdapi_lsp_log.txt file

File: src/lsp/lp_lsp.ml (hunk 3 above)
Comment (Alidra) [reply src/lsp/lp_lsp.ml]: No. The exception will be caught at the end of the function (line 456) and the message discarded. I changed the message though.
